name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_KEY }}" > ~/.ssh/vm_key.pem
        chmod 600 ~/.ssh/vm_key.pem

    - name: Clean remote directory
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/vm_key.pem azureuser@4.246.142.4 "
          sudo pkill node || true;
          rm -rf ~/akshat-app;
          mkdir -p ~/akshat-app;
        "

    - name: Copy project files
      run: scp -o StrictHostKeyChecking=no -i ~/.ssh/vm_key.pem -r * azureuser@4.246.142.4:~/akshat-app

    - name: Start server on VM
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/vm_key.pem azureuser@4.246.142.4 "
          cd ~/akshat-app;
          npm install;
          sudo nohup node server.js > app.log 2>&1 &
        "
